global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'service', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  receiver: 'default'
  routes:
    - match:
        severity: 'critical'
      receiver: 'omni-notifications'
      continue: true
    - match:
        severity: 'critical'
      receiver: 'omni-notifications-mock'
      continue: true
    - match:
        severity: 'critical'
      receiver: 'default'
    - match:
        severity: 'warning'
      receiver: 'default'
    - match:
        service: 'omni-unified'
      receiver: 'omni-notifications'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance', 'job']

receivers:
  - name: 'default'
    email_configs:
      - to: 'robertpezdirc@gmail.com'
        from: 'robertpezdirc12@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        require_tls: true
        auth_username: 'robertpezdirc12@gmail.com'
        auth_password: 'imxlrqoayoomkpvd'

  - name: 'omni-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})'
        text: |
          *Alert:* {{ .CommonAnnotations.summary }}\n
          *Description:* {{ .CommonAnnotations.description }}\n
          *Service:* {{ .CommonLabels.service }}\n
          *Status:* {{ .Status }}\n
          *Labels:* {{ .CommonLabels }}\n
  - name: 'omni-notifications-mock'
    slack_configs:
      - api_url: 'http://mock-slack:9001/webhook'
        channel: '#omni-notifications'
        send_resolved: true
        title: '{{ .CommonLabels.alertname }} ({{ .CommonLabels.severity }})'
        text: |
          *Alert:* {{ .CommonAnnotations.summary }}\n
          *Description:* {{ .CommonAnnotations.description }}\n
          *Service:* {{ .CommonLabels.service }}\n
          *Status:* {{ .Status }}\n
          *Labels:* {{ .CommonLabels }}\n
