apiVersion: 1
datasources:
  - name: JSON API (Custom)
    uid: json_api
    type: marcusolsson-json-datasource
    access: proxy
    url: ${CUSTOM_JSON_API_URL}
    isDefault: false
    jsonData:
      httpMethod: GET
      timeout: 60
    editable: true